Numpy : Numerical python
Exploratory data analysis
pandas sklearn tenserflow require python
NumPy is a core Python library for numerical computing, built for handling large arrays and matrices efficiently. It is significantly faster than Python's built-in lists because it uses optimized C language style storage where actual values are stored at contiguous locations (not object reference). It also supports vectorized computations.

ndarray object: Stores homogeneous data in n-dimensional arrays for fast processing.
Vectorized operations: Perform element-wise calculations without explicit loops.
Broadcasting: Apply operations across arrays of different shapes.
Linear algebra functions: Matrix multiplication, inversion, eigenvalues, etc.
Statistical tools: Mean, median, standard deviation, and more.
Fourier transforms: Fast computation for signal and image processing.
Integration with other libraries: Works seamlessly with Pandas, SciPy, and scikit-learn.
What is NumPy Used for?
With NumPy, you can perform a wide range of numerical operations, including:

Creating and manipulating arrays.
Performing element-wise and matrix operations.
Generating random numbers and statistical calculations.
Conducting linear algebra operations.
Working with Fourier transformations.
Handling missing values efficiently in datasets.
Why Learn NumPy?
NumPy speeds up math operations like addition and multiplication on large groups of numbers compared to regular Python..
It’s good for handling large lists of numbers (arrays), so you don’t have to write complicated loops.
It gives ready-to-use functions for statistics, algebra and random numbers.
Libraries like Pandas, SciPy, TensorFlow and many others are built on top of NumPy.
NumPy uses less memory and stores data more efficiently, which matters when working with lots of data.
NumPy Basics
This section covers the fundamentals of NumPy, including installation, importing the library and understanding its core functionalities. You will learn about the advantages of NumPy over Python lists and how to set up your environment for efficient numerical computing.

Introduction
Installing
Understanding

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
L=[1,2,3,4,5]
L

[1, 2, 3, 4, 5]

In [ ]:
import numpy as np

arr1 = np.array(L)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

# Fixed: Each nested list now has a consistent shape (2x2x2)
arr3 = np.array([[[1, 2,3,4], [22,3,2, 4]], [[4,1,5,6], [5,77 ,5, 8]]])
print(arr3)

[[[ 1  2  3  4]
  [22  3  2  4]]

 [[ 4  1  5  6]
  [ 5 77  5  8]]]


In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
type(np.ndarray)

type

In [ ]:
np.ndarray

numpy.ndarray

In [2]:
import numpy as np

L = [1,2,3,4,5]
arr_L = np.array(L)
arr_L.shape

(5,)

In [ ]:
arr2.shape
arr3.shape

(2, 2, 2)

In [ ]:
L[-1]

5

In [ ]:
L[2:4]

[3, 4]

In [ ]:
arr2[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[::,1]

array([2, 5])

In [ ]:
arr2[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [ ]:
arr3[::,1]

array([[2, 4],
       [5, 8]])

In [ ]:
arr3

array([[[ 1,  2,  3,  4],
        [22,  3,  2,  4]],

       [[ 4,  1,  5,  6],
        [ 5, 77,  5,  8]]])

In [ ]:
arr3[1,:,2:4]

array([[5, 6],
       [5, 8]])

In [ ]:
np.random.randint(1,4,(2,3))

array([[3, 3, 1],
       [3, 1, 2]])

In [ ]:
np.full((3,3,4),10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
mat1=np.array([[1,2,3],[2,3,6]])
mat2=np.array([[12,5,3],[1,32,26]])
mat1+mat2

array([[13,  7,  6],
       [ 3, 35, 32]])

In [ ]:
mat4=np.array([[1,3],[2,4],[5,7]])

In [ ]:
# Use @ or np.dot() for matrix multiplication
mat1 @ mat4

array([[20, 32],
       [38, 60]])

In [ ]:
np.linspace(-90, 90, 180)

array([-90.        , -88.99441341, -87.98882682, -86.98324022,
       -85.97765363, -84.97206704, -83.96648045, -82.96089385,
       -81.95530726, -80.94972067, -79.94413408, -78.93854749,
       -77.93296089, -76.9273743 , -75.92178771, -74.91620112,
       -73.91061453, -72.90502793, -71.89944134, -70.89385475,
       -69.88826816, -68.88268156, -67.87709497, -66.87150838,
       -65.86592179, -64.8603352 , -63.8547486 , -62.84916201,
       -61.84357542, -60.83798883, -59.83240223, -58.82681564,
       -57.82122905, -56.81564246, -55.81005587, -54.80446927,
       -53.79888268, -52.79329609, -51.7877095 , -50.78212291,
       -49.77653631, -48.77094972, -47.76536313, -46.75977654,
       -45.75418994, -44.74860335, -43.74301676, -42.73743017,
       -41.73184358, -40.72625698, -39.72067039, -38.7150838 ,
       -37.70949721, -36.70391061, -35.69832402, -34.69273743,
       -33.68715084, -32.68156425, -31.67597765, -30.67039106,
       -29.66480447, -28.65921788, -27.65363128, -26.64

In [ ]:
a=np.random.randint(10,size=(3,4))

In [ ]:
b=np.random.randint(5,size=(3,3,4))